/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/**
 * Scrub demo-environment identity tokens from ES docs.
 *
 * Background: when demo hosts are provisioned on real VMs, host activity is
 * generated by the provisioning/installer account. Endpoint detections fire
 * against that account, so Defend alerts end up with user.name = '<installer>',
 * and the Windows profile path leaks into file/process events, Attack
 * Discovery documents, and Case activity. If the forensic-analysis or
 * response-actions skills read that data, the LLM may conclude "this looks
 * like a demo owned by <installer>" instead of analyzing the attack story.
 *
 * This script replaces those identity tokens with a neutral service-account
 * name in-place, using a case-insensitive painless script (covers ALL casings
 * of the token, plus the Windows 8.3 short-name form e.g. `PATRYK~1` that
 * appears in Temp paths when the user profile dir exceeds 8 chars).
 *
 * Index coverage: the indices where a VM installer token was observed to
 * leak during the BlackHat demo (2026-09):
 *   - logs-endpoint.events.*          (user.name, file.path)
 *   - .alerts-security.alerts-default (kibana.alert.reason prose)
 *   - .adhoc.alerts-security.attack.discovery.alerts-default
 *   - logs-endpoint.alerts-default
 *   - .cases, .cases-activity
 *
 * Runs one scoped _update_by_query per target index. Idempotent — a re-run
 * after success updates 0 docs.
 *
 * Usage (from kibana repo root):
 *   node --require ./src/setup_node_env \
 *     scripts/endpoint/blackhat_demo/scrub_demo_identity.ts \
 *     --node https://es.example:9243 --username elastic --password <pw> \
 *     [--token patrykkopycinski] [--replacement svc-install] [--dry-run]
 */

import { Client } from '@elastic/elasticsearch';
import { run } from '@kbn/dev-cli-runner';

/** Indices known to contain installer-account leaks (BlackHat demo 2026-09 sweep) */
export const TARGET_INDICES = [
  'logs-endpoint.events.*',
  '.alerts-security.alerts-default',
  '.adhoc.alerts-security.attack.discovery.alerts-default',
  'logs-endpoint.alerts-default',
  '.cases',
  '.cases-activity',
] as const;

/**
 * Build the from→to replacement pairs. Case-insensitivity is handled in the
 * painless script (Substring + StringBuilder — String.replaceAll is NOT on
 * the painless whitelist), so only the lowercase canonical token plus its
 * Windows 8.3 short-name form are needed here.
 */
export function buildPairs(
  token: string,
  replacement: string
): Array<{ from: string; to: string }> {
  const pairs: Array<{ from: string; to: string }> = [{ from: token, to: replacement }];

  // Windows 8.3 short name: first 6 chars upper + ~1 (e.g. PATRYK~1)
  if (token.length > 6 && replacement.length > 6) {
    pairs.push({
      from: `${token.slice(0, 6).toUpperCase()}~1`,
      to: `${replacement.slice(0, 6).toUpperCase()}~1`,
    });
  }

  return pairs;
}

export const PAINLESS_SOURCE = `
String replaceIgnoreCase(String s, String from, String to) {
  if (from.length() == 0) { return s; }
  String lowerS = s.toLowerCase();
  String lowerFrom = from.toLowerCase();
  StringBuilder sb = new StringBuilder();
  int i = 0;
  int idx = lowerS.indexOf(lowerFrom, i);
  while (idx >= 0) {
    sb.append(s.substring(i, idx));
    sb.append(to);
    i = idx + from.length();
    idx = lowerS.indexOf(lowerFrom, i);
  }
  sb.append(s.substring(i));
  return sb.toString();
}

String scrubStr(String s, List pairs) {
  for (def p : pairs) {
    s = replaceIgnoreCase(s, (String) p.get('from'), (String) p.get('to'));
  }
  return s;
}

void scrubList(List l, List pairs) {
  for (int i = 0; i < l.size(); i++) {
    def v = l.get(i);
    if (v instanceof String) { l.set(i, scrubStr((String) v, pairs)); }
    else if (v instanceof Map) { scrubMap(v, pairs); }
    else if (v instanceof List) { scrubList(v, pairs); }
  }
}

void scrubMap(Map m, List pairs) {
  for (def e : m.entrySet()) {
    def v = e.getValue();
    if (v instanceof String) { e.setValue(scrubStr((String) v, pairs)); }
    else if (v instanceof Map) { scrubMap(v, pairs); }
    else if (v instanceof List) { scrubList(v, pairs); }
  }
}

scrubMap(ctx._source, params.pairs);
`;

run(
  async ({ log, flags }) => {
    const node = flags.node as string;
    const username = (flags.username as string | undefined) ?? 'elastic';
    const password = flags.password as string | undefined;
    const token = (flags.token as string | undefined) ?? 'patrykkopycinski';
    const replacement = (flags.replacement as string | undefined) ?? 'svc-install';
    const dryRun = Boolean(flags['dry-run']);

    if (!node) {
      throw new Error('--node <elasticsearch url> is required');
    }
    if (!password) {
      throw new Error('--password is required');
    }

    const client = new Client({ node, auth: { username, password } });
    const pairs = buildPairs(token, replacement);
    const query = `*${token}* OR *${token.slice(0, 6).toUpperCase()}~1*`;

    log.info(`token=${token} -> replacement=${replacement}`);
    log.info(`pairs: ${JSON.stringify(pairs)}`);

    if (dryRun) {
      for (const index of TARGET_INDICES) {
        const count = await client.count({
          index,
          expand_wildcards: 'all',
          query: { query_string: { query } },
        });
        if (count.count > 0) {
          log.info(`  ${index}: ${count.count} docs would be updated`);
        }
      }
      return;
    }

    // One scoped _update_by_query per target index — the approach proven
    // during the manual BlackHat demo scrub (2026-09).
    let totalUpdated = 0;
    const failures: string[] = [];

    for (const index of TARGET_INDICES) {
      const result = await client.updateByQuery({
        index,
        expand_wildcards: 'all',
        conflicts: 'proceed',
        refresh: true,
        query: { query_string: { query } },
        script: { lang: 'painless', source: PAINLESS_SOURCE, params: { pairs } },
      });

      const updated = result.updated ?? 0;
      totalUpdated += updated;
      if (updated > 0) {
        log.info(`  ${index}: updated=${updated}`);
      }
      for (const f of result.failures ?? []) {
        failures.push(`${index}: ${JSON.stringify(f).slice(0, 500)}`);
      }
    }

    if (failures.length > 0) {
      throw new Error(`update failures:\n${failures.join('\n')}`);
    }
    log.info(`total updated=${totalUpdated}`);

    // Verify: re-count every index — all must be 0
    let residual = 0;
    for (const index of TARGET_INDICES) {
      const count = await client.count({
        index,
        expand_wildcards: 'all',
        query: { query_string: { query } },
      });
      if (count.count > 0) {
        log.error(`  ${index}: ${count.count} docs still match`);
        residual += count.count;
      }
    }
    if (residual > 0) {
      throw new Error(`verify failed: ${residual} docs still match '${token}'`);
    }
    log.success(`verified: 0 docs remain matching '${token}'`);
  },
  {
    description:
      'Scrubs VM installer-account identity tokens from demo ES docs (endpoint events, alerts, attack discovery, cases)',
    flags: {
      string: ['node', 'username', 'password', 'token', 'replacement'],
      boolean: ['dry-run'],
      help: `
        --node         Elasticsearch URL of the deployed project (required)
        --username     ES username (default: elastic)
        --password     ES password (required)
        --token        Identity token to scrub (default: patrykkopycinski)
        --replacement  Neutral replacement name (default: svc-install)
        --dry-run      Only count matching docs, do not update
      `,
    },
  }
);
