/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import { z } from '@kbn/zod/v4';
import { ToolType, ToolResultType } from '@kbn/agent-builder-common';
import type { BuiltinToolDefinition } from '@kbn/agent-builder-server';
import type { Logger } from '@kbn/logging';
import { ARGUS_SOC_INDICES } from '@kbn/argus-console-common';
import type { SecuritySolutionPluginCoreSetupDependencies } from '../../../plugin_contract';
import { getAgentBuilderResourceAvailability } from '../../utils/get_agent_builder_resource_availability';
import { ARGUS_EXPORT_NAVIGATOR_LAYER_TOOL_ID } from './constants';

const TECHNIQUE_ID_REGEX = /^T\d{4}(\.\d{3})?$/;

const exportNavigatorLayerSchema = z
  .object({
    name: z
      .string()
      .min(1)
      .max(120)
      .default('Argus coverage layer')
      .describe('Human-readable layer name. Shown in the ATT&CK Navigator top bar.'),
    profile_id: z
      .string()
      .optional()
      .describe('Optional threat-profile id. When provided, layer is scoped to its techniques.'),
    technique_ids: z
      .array(z.string().regex(TECHNIQUE_ID_REGEX))
      .optional()
      .describe('Explicit technique list. Overrides profile_id when both are given.'),
    description: z
      .string()
      .max(300)
      .default('Generated by Argus — score = argus_authored - community_authored per technique.')
      .describe('Layer description rendered under the layer name.'),
  })
  .refine((v) => v.profile_id || (v.technique_ids && v.technique_ids.length > 0), {
    message: 'Either profile_id or technique_ids is required.',
  });

interface ThreatProfileDoc {
  profile_id?: string;
  technique_ids?: string[];
}

interface CorpusBucket {
  key: string;
  doc_count: number;
  by_source?: { buckets?: Array<{ key: string; doc_count: number }> };
}

/**
 * Produces an ATT&CK Navigator v4.5 layer JSON. The score is a signed
 * `argus_authored - community_authored` delta per technique, read from
 * `.soc-detection-corpus`. Returned as a string so callers can pipe
 * straight to `download` without re-serialising.
 */
export function argusExportNavigatorLayerTool(
  core: SecuritySolutionPluginCoreSetupDependencies,
  logger: Logger
): BuiltinToolDefinition<typeof exportNavigatorLayerSchema> {
  return {
    id: ARGUS_EXPORT_NAVIGATOR_LAYER_TOOL_ID,
    type: ToolType.builtin,
    description:
      'Export an ATT&CK Navigator v4.5 layer JSON covering the selected techniques. Score = ' +
      'argus_authored - community_authored. Provide `profile_id` to scope to a threat-profile ' +
      'or `technique_ids` for an explicit set.',
    schema: exportNavigatorLayerSchema,
    tags: ['security', 'argus', 'argus:playbook', 'read', 'coverage', 'export'],
    availability: {
      cacheMode: 'space',
      handler: async ({ request }) =>
        getAgentBuilderResourceAvailability({ core, request, logger }),
    },
    handler: async ({ name, profile_id: profileId, technique_ids, description }, { esClient }) => {
      try {
        let techniqueIds: string[] = technique_ids ? [...technique_ids] : [];

        if (techniqueIds.length === 0 && profileId) {
          const profileRes = await esClient.asCurrentUser.search<ThreatProfileDoc>({
            index: ARGUS_SOC_INDICES.threatProfiles,
            size: 1,
            query: { term: { profile_id: profileId } },
            ignore_unavailable: true,
          });
          const profile = profileRes.hits.hits[0]?._source;
          techniqueIds =
            profile && Array.isArray(profile.technique_ids) ? profile.technique_ids : [];
        }

        if (techniqueIds.length === 0) {
          return {
            results: [
              {
                type: ToolResultType.other,
                data: {
                  message: `No techniques resolved${profileId ? ` for profile=${profileId}` : ''}.`,
                  technique_count: 0,
                  layer_json: null,
                },
              },
            ],
          };
        }

        const corpusRes = await esClient.asCurrentUser.search({
          index: ARGUS_SOC_INDICES.detectionCorpus,
          size: 0,
          query: {
            bool: { filter: [{ terms: { mitre_technique: techniqueIds } }] },
          },
          aggs: {
            by_technique: {
              terms: { field: 'mitre_technique', size: techniqueIds.length * 2 },
              aggs: {
                by_source: { terms: { field: 'source', size: 20 } },
              },
            },
          },
          ignore_unavailable: true,
        });

        const aggs = corpusRes.aggregations as
          | { by_technique?: { buckets?: CorpusBucket[] } }
          | undefined;

        const deltaByTechnique = (aggs?.by_technique?.buckets ?? []).reduce<
          Record<string, { score: number; argus: number; community: number }>
        >((acc, bucket) => {
          const sources = bucket.by_source?.buckets ?? [];
          const argus = sources
            .filter((s) => s.key === 'argus' || s.key.startsWith('argus.'))
            .reduce((sum, s) => sum + s.doc_count, 0);
          const community = Math.max(0, bucket.doc_count - argus);
          acc[bucket.key] = { score: argus - community, argus, community };
          return acc;
        }, {});

        const techniques = techniqueIds.map((id) => {
          const stats = deltaByTechnique[id] ?? { score: 0, argus: 0, community: 0 };
          const color = stats.score > 0 ? '#2E7D32' : stats.score < 0 ? '#C62828' : '#BDBDBD';
          return {
            techniqueID: id,
            score: stats.score,
            color,
            comment: `argus=${stats.argus}, community=${stats.community}`,
            enabled: true as const,
          };
        });

        const layer = {
          name,
          description,
          domain: 'enterprise-attack' as const,
          versions: { attack: '14', navigator: '4.9.1', layer: '4.5' },
          techniques,
          gradient: {
            colors: ['#C62828', '#BDBDBD', '#2E7D32'] as const,
            minValue: -5,
            maxValue: 5,
          },
          legendItems: [
            { label: 'Argus over-covers', color: '#2E7D32' },
            { label: 'Balanced / untouched', color: '#BDBDBD' },
            { label: 'Community-only', color: '#C62828' },
          ],
        };

        return {
          results: [
            {
              type: ToolResultType.other,
              data: {
                message: `Exported Navigator layer with ${techniques.length} technique(s).`,
                technique_count: techniques.length,
                layer_json: JSON.stringify(layer, null, 2),
              },
            },
          ],
        };
      } catch (error) {
        logger.error(
          `argus.export_navigator_layer failed: ${
            error instanceof Error ? error.message : String(error)
          }`
        );
        return {
          results: [
            {
              type: ToolResultType.error,
              data: {
                message: `Failed to export Navigator layer: ${
                  error instanceof Error ? error.message : String(error)
                }`,
              },
            },
          ],
        };
      }
    },
  };
}
