export { getEsClient, getLinkedEsClient, getKbnClient } from './clients';
export { createScoutConfig } from './config';
export { getEsArchiver, getLinkedEsArchiver } from './es_archiver';
export { createKbnUrl } from './kibana_url';
export { createSamlSessionManager } from './saml_auth';
export type { KibanaUrl } from './kibana_url';
export type { SamlSessionManager } from '@kbn/test-saml-auth';
export { ScoutLogger } from './logger';
export type { KbnClient } from '@kbn/kbn-client';
export type { Client as EsClient } from '@elastic/elasticsearch';
export { createCustomRole, createElasticsearchCustomRole, isElasticsearchRole, } from './custom_role';
export type { ElasticsearchRoleDescriptor, KibanaRole } from './custom_role';
export { getPrivilegedRoleName } from './roles';
