import type { AppMenuConfig } from '@kbn/app-menu';
import type { AppHeaderBack as CoreAppHeaderBack, AppHeaderBadge as CoreAppHeaderBadge, AppHeaderBadgeItem as CoreAppHeaderBadgeItem, AppHeaderConfig as CoreAppHeaderConfig, ChromeAppHeaderConfig as CoreChromeAppHeaderConfig, AppHeaderDescription as CoreAppHeaderDescription, AppHeaderEditableTitle as CoreAppHeaderEditableTitle, AppHeaderFavoriteAction as CoreAppHeaderFavoriteAction, AppHeaderFavoriteStatus as CoreAppHeaderFavoriteStatus, AppHeaderShareAction as CoreAppHeaderShareAction, AppHeaderMetadataButtonItem as CoreAppHeaderMetadataButtonItem, AppHeaderMetadataHealthItem as CoreAppHeaderMetadataHealthItem, AppHeaderMetadataItem as CoreAppHeaderMetadataItem, AppHeaderMetadataItems as CoreAppHeaderMetadataItems, AppHeaderMetadataTextItem as CoreAppHeaderMetadataTextItem, AppHeaderSpacing as CoreAppHeaderSpacing, AppHeaderTab as CoreAppHeaderTab, AppHeaderTabAction as CoreAppHeaderTabAction, AppHeaderTabActions as CoreAppHeaderTabActions, AppHeaderTabBadge as CoreAppHeaderTabBadge, AppHeaderTabIconBadge as CoreAppHeaderTabIconBadge, AppHeaderTitle as CoreAppHeaderTitle, AppHeaderTitleSaveResult as CoreAppHeaderTitleSaveResult } from '@kbn/core-chrome-browser';
export type AppHeaderMenu = AppMenuConfig;
export type AppHeaderBack = CoreAppHeaderBack;
export type AppHeaderBadge = CoreAppHeaderBadge;
export type AppHeaderBadgeItem = CoreAppHeaderBadgeItem;
export type AppHeaderConfig = CoreAppHeaderConfig;
export type ChromeAppHeaderConfig = CoreChromeAppHeaderConfig;
export type AppHeaderDescription = CoreAppHeaderDescription;
export type AppHeaderEditableTitle = CoreAppHeaderEditableTitle;
export type AppHeaderFavoriteAction = CoreAppHeaderFavoriteAction;
export type AppHeaderFavoriteStatus = CoreAppHeaderFavoriteStatus;
export type AppHeaderShareAction = CoreAppHeaderShareAction;
export type AppHeaderMetadataButtonItem = CoreAppHeaderMetadataButtonItem;
export type AppHeaderMetadataHealthItem = CoreAppHeaderMetadataHealthItem;
export type AppHeaderMetadataItem = CoreAppHeaderMetadataItem;
export type AppHeaderMetadataItems = CoreAppHeaderMetadataItems;
export type AppHeaderMetadataTextItem = CoreAppHeaderMetadataTextItem;
export type AppHeaderTab = CoreAppHeaderTab;
export type AppHeaderTabAction = CoreAppHeaderTabAction;
export type AppHeaderTabActions = CoreAppHeaderTabActions;
export type AppHeaderTabBadge = CoreAppHeaderTabBadge;
export type AppHeaderTabIconBadge = CoreAppHeaderTabIconBadge;
export type AppHeaderTitle = CoreAppHeaderTitle;
export type AppHeaderTitleSaveResult = CoreAppHeaderTitleSaveResult;
export type AppHeaderSpacing = CoreAppHeaderSpacing;
