/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

export {
  buildReasoningChainFromSpanDocs,
  type SpanDocInput,
} from './src/builders/reasoning_chain_builder';

export {
  buildMutationLineageFromDocs,
  type MutationStageDocs,
  type StageDoc,
} from './src/builders/mutation_lineage_builder';

export {
  buildGovernancePulse,
  type ActorTrustTiersAggsInput,
  type BuildGovernancePulseArgs,
  type GovernancePulseAggsInput,
  type MutationIntentsAggsInput,
} from './src/builders/governance_pulse_builder';

export {
  buildActivityFeed,
  hitToEvent,
  allActivityLayers,
  type BuildActivityFeedArgs,
  type RawActivityHit,
} from './src/builders/activity_feed_builder';

export {
  buildMutations,
  type BuildMutationsArgs,
  type RawMutationIntentDoc,
  type RawOutcomeDoc,
} from './src/builders/mutations_builder';

export {
  buildMutationDetail,
  type BuildMutationDetailArgs,
  type DetailRawAdvisoryDoc,
  type DetailRawBacktestDoc,
  type DetailRawMutationIntentDoc,
  type DetailRawOutcomeDoc,
} from './src/builders/mutation_detail_builder';

export {
  buildE2dFlow,
  type BuildE2dFlowArgs,
  type E2dRawAdvisoryDoc,
  type E2dRawBacktestDoc,
  type E2dRawEvalRunDoc,
  type E2dRawMutationIntentDoc,
  type E2dRawOutcomeDoc,
  type E2dRawRecommendationDoc,
} from './src/builders/e2d_flow_builder';

export {
  buildRecentProposals,
  buildSynthesisProposals,
  dominates,
  findDominator,
  type BuildRecentProposalsInput,
  type BuildSynthesisProposalsInput,
  type SynthesisRawAdvisoryDoc,
  type SynthesisRawBlock,
  type SynthesisRawCandidate,
  type SynthesisRawRecommendationDoc,
} from './src/builders/synthesis_proposals_builder';

export {
  buildAutonomyDecisions,
  hitToDecision,
  type BuildAutonomyDecisionsArgs,
  type RawAutonomyDecisionDoc,
  type RawAutonomyHit,
} from './src/builders/autonomy_decisions_builder';

export {
  buildCoverageGaps,
  hitToGap,
  type BuildCoverageGapsArgs,
  type RawCoverageGapDoc,
  type RawCoverageHit,
} from './src/builders/coverage_gaps_builder';

export {
  buildCalderaQueue,
  type BuildCalderaQueueArgs,
  type RawCalderaCommandDoc,
  type RawCalderaProfileDoc,
  type RawDifficultyStateDoc,
} from './src/builders/caldera_queue_builder';

export {
  buildKillSwitchState,
  type BuildKillSwitchArgs,
  type RawKillSwitchDoc,
} from './src/builders/kill_switch_builder';

export {
  buildActorCoverage,
  buildCoverageSnapshot,
  buildNavigatorLayer,
  type RawAuthoredDoc,
  type RawCorpusDoc,
  type TechniqueMeta,
} from './src/builders/coverage_builder';

export type {
  InjectionSurfaceFlag,
  ReasoningChain,
  ReasoningChainBuildResult,
  ReasoningChainReasonCode,
  ReasoningChainSubject,
  ReasoningStep,
  ReasoningStepType,
  TrustTier,
  LineageEdge,
  LineageEdgeKind,
  LineageNode,
  LineageNodeStatus,
  LineageNodeType,
  MutationLineage,
  MutationLineageBuildResult,
  MutationLineageReasonCode,
  MutationLineageSubject,
  MutationLineageSubjectKind,
  ArgusE2dAppliedStage,
  ArgusE2dBacktestedStage,
  ArgusE2dEvaluatedStage,
  ArgusE2dExploitProbabilityStage,
  ArgusE2dFlowPayload,
  ArgusE2dFlowResponse,
  ArgusE2dGovernanceStage,
  ArgusE2dIngestedStage,
  ArgusE2dOverallStatus,
  ArgusE2dReasonCode,
  ArgusE2dRecentCve,
  ArgusE2dRecentCvesResponse,
  ArgusE2dRunningStage,
  ArgusE2dStage,
  ArgusE2dStageBase,
  ArgusE2dStageKind,
  ArgusE2dStageStatus,
  ArgusE2dSynthesizedStage,
  GovernancePulse,
  GovernancePulseBuildResult,
  GovernancePulseDrift,
  GovernancePulseMttr,
  GovernancePulseThroughput,
  GovernancePulseTierMix,
  ActivityEvent,
  ActivityFeedFilters,
  ActivityFeedResponse,
  ActivityLayer,
  ActivityPressure,
  ArgusEventSample,
  ArgusEventSampleClassification,
  ArgusMutationCounts,
  ArgusMutationDetail,
  ArgusMutationDetailActor,
  ArgusMutationDetailAdvisory,
  ArgusMutationDetailAudit,
  ArgusMutationDetailBacktest,
  ArgusMutationDetailCoverageDelta,
  ArgusMutationDetailGate,
  ArgusMutationDetailOutcome,
  ArgusMutationDetailPatternSeed,
  ArgusMutationDetailReasonCode,
  ArgusMutationDetailResponse,
  ArgusMutationDetailRuleDelta,
  ArgusMutationDetailSourceSignal,
  ArgusMutationPostApplyObservation,
  ArgusMutationFilter,
  ArgusMutationRow,
  ArgusMutationVerdict,
  ArgusMutationWindow,
  ArgusMutationsResponse,
  ArgusSynthesisComposition,
  ArgusSynthesisDominationReason,
  ArgusSynthesisPredicted,
  ArgusSynthesisProposal,
  ArgusSynthesisProposalTier,
  ArgusSynthesisRecentResponse,
  ArgusSynthesisRecentRow,
  ArgusSynthesisResponse,
  ArgusSynthesisWeights,
  ArgusSynthesisWindow,
  ArgusVariantAxisName,
  ArgusAutonomyCounts,
  ArgusAutonomyDecision,
  ArgusAutonomyFinalStatus,
  ArgusAutonomyResponse,
  ArgusAutonomyWindow,
  ArgusCoverageCounts,
  ArgusCoverageGap,
  ArgusCoverageResponse,
  ArgusCoverageSeverity,
  ArgusCoverageWindow,
  ArgusCalderaCommand,
  ArgusCalderaCommandStatus,
  ArgusCalderaCounts,
  ArgusCalderaDifficultyState,
  ArgusCalderaProfile,
  ArgusCalderaQueueResponse,
  ArgusKillSwitchResponse,
  ArgusKillSwitchState,
  ArgusKillSwitchToggleRequest,
  ArgusKillSwitchToggleResponse,
  ArgusMutationVerdictAction,
  ArgusMutationVerdictRequest,
  ArgusMutationVerdictResponse,
  ArgusActorCoverage,
  ArgusCoverageCell,
  ArgusCoverageSnapshot,
  ArgusNavigatorLayer,
  ArgusThreatActor,
  ArgusThreatProfile,
  ArgusPlaybook,
  ArgusPlaybookIndexResponse,
  ArgusPlaybookKind,
  ArgusPlaybookUserIntent,
  DecisionGraphEdge,
  DecisionGraphNode,
  DecisionGraphNodeKind,
  DecisionGraphRecentRoot,
  DecisionGraphRecentRootsResponse,
  DecisionGraphRequest,
  DecisionGraphResponse,
  ArgusArtifactDetails,
  ArgusArtifactDetailsReasonCode,
  ArgusArtifactRelated,
  ArgusArtifactRelatedActor,
  ArgusArtifactRelatedAlert,
  ArgusArtifactRelatedKind,
  ArgusArtifactRelatedMutationIntent,
  ArgusArtifactRelatedOutcome,
  ArgusArtifactRelatedReasoningTrace,
  ArgusArtifactRelatedRule,
} from './src/types';

export {
  ARGUS_PLAYBOOK_TAG,
  CANONICAL_STAGE_ORDER,
  ARGUS_ARTIFACT_RELATED_KINDS,
} from './src/types';

export {
  REASONING_CHAIN_ROUTE,
  MUTATION_LINEAGE_ROUTE,
  GOVERNANCE_PULSE_ROUTE,
  ACTIVITY_FEED_ROUTE,
  MUTATIONS_ROUTE,
  MUTATION_DETAIL_ROUTE,
  E2D_FLOW_ROUTE,
  E2D_RECENT_CVES_ROUTE,
  SYNTHESIS_PROPOSALS_ROUTE,
  RECENT_PROPOSALS_ROUTE,
  AUTONOMY_DECISIONS_ROUTE,
  COVERAGE_GAPS_ROUTE,
  CALDERA_QUEUE_ROUTE,
  KILL_SWITCH_ROUTE,
  MUTATION_VERDICT_ROUTE,
  COVERAGE_ROUTE,
  THREAT_PROFILES_ROUTE,
  THREAT_PROFILE_DETAIL_ROUTE,
  THREAT_ACTORS_ROUTE,
  THREAT_ACTOR_DETAIL_ROUTE,
  THREAT_ACTOR_COVERAGE_ROUTE,
  NAVIGATOR_LAYER_ROUTE,
  REDUNDANCY_SUMMARY_ROUTE,
  DECISION_GRAPH_ROUTE,
  DECISION_GRAPH_RECENT_ROOTS_ROUTE,
  PLAYBOOKS_INDEX_ROUTE,
  ARTIFACT_DETAILS_ROUTE,
  ARGUS_CONSOLE_READ_UI_CAPABILITY,
  ARGUS_CONSOLE_ALL_UI_CAPABILITY,
  ARGUS_WRITE_API_CAPABILITY,
  ARGUS_SOC_INDICES,
  KILL_SWITCH_DOC_ID,
} from './src/constants';
